### PR TITLE
Remove default slurm partition option

### PR DESCRIPTION
**Pull request by iseessel**
I am a bit worried this may break somebody's workflow? We might want to have our own internal defaults in order to ensure backwards compatability.

### CODE REVIEW

**Review by prigoyal — APPROVED** [review]
makes sense to me!

**Comment by QuentinDuval** [comment]
Make sense to me too. +1 for merging it !

**Comment by prigoyal** [comment]
this needs to be rebased and then reimported to phabricator to land :)

**Comment by iseessel** [comment]
> this needs to be rebased and then reimported to phabricator to land :)

Done! @prigoyal

**Pull request closed without merging**
